version: '2'

services:
## SETUP MAGENTO ##
    setup:
        build: docker/phpfpm
        restart: always
        container_name: marketplace_setup
        volumes:
            - ./src:/src/www
        command: /bin/sh -c "chmod +x -R ./setup-mage && ./setup-mage"
        environment:
            - MAGE_SETUP_DB_HOST=percona
            - MAGE_SETUP_DB_NAME=MAGE_TEST
            - MAGE_SETUP_DB_USER=mage
            - MAGE_SETUP_DB_PASSWORD=mage
            - MAGE_SETUP_BASE_URL=http://it.mage-two/
            - MAGE_SETUP_ADMIN_BACKEND_FRONTNAME=admin
            - MAGE_SETUP_ADMIN_FIRSTNAME=Owner
            - MAGE_SETUP_ADMIN_LASTNAME=Mage
            - MAGE_SETUP_ADMIN_EMAIL=owner@mage.com
            - MAGE_SETUP_ADMIN_USER=admin
            - MAGE_SETUP_ADMIN_PASSWORD=12345qw
        networks:
            - network-back

    unit-test:
        build: docker/phpfpm
        restart: always
        container_name: marketplace_unit-test
        volumes:
            - ./src:/src/www
        command: /bin/sh -c "php -d memory_limit=2G vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist"
        networks:
            - network-back