version: '2'

services:
## MAIN SERVICES ##
    web:
        build: docker/nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./src:/src/www
        links:  # o link define a ordem de build ;)
           - phpfpm
        networks:
            - network-back

    phpfpm:
        build: docker/phpfpm
        restart: always
        volumes:
            - ./src:/src/www
            - ./docker/setup-mage:/src/setup-mage
        environment:
            - MAGE_SETUP_DB_HOST=percona
            - MAGE_SETUP_DB_NAME=MAGE_TEST
            - MAGE_SETUP_DB_USER=mage
            - MAGE_SETUP_DB_PASSWORD=mage
            - MAGE_SETUP_BASE_URL=http://it.mage-two/
            - MAGE_SETUP_ADMIN_BACKEND_FRONTNAME=admin
            - MAGE_SETUP_ADMIN_FIRSTNAME=Owner
            - MAGE_SETUP_ADMIN_LASTNAME=Mage
            - MAGE_SETUP_ADMIN_EMAIL=owner@mage.com
            - MAGE_SETUP_ADMIN_USER=admin
            - MAGE_SETUP_ADMIN_PASSWORD=12345qw
        networks:
            - network-back

## LOCAL TOOLS ##      
    percona:
        image: percona
        restart: always
        container_name: percona_development
        volumes:
            - ./docker/mysql/data/percona:/var/lib/mysql
            - ./docker/mysql/dumps:/dumps
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=MAGE_TEST
            - MYSQL_USER=mage
            - MYSQL_PASSWORD=mage
        networks:
            - network-back

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        container_name: phpmyadmin_development
        environment:
            PMA_ARBITRARY: 1
        ports:
            - 8888:80
        volumes:
            - /sessions
        networks:
            - network-back

networks:
    network-back:
        driver: bridge