version: '2'

services:
    web:
        build: docker/nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./src:/src/www
        links:
           - phpfpm
        networks:
            - network-back

    phpfpm:
        build: docker/phpfpm
        restart: always
        volumes:
            - ./src:/src/www
            - ./docker/setup-mage.sh:/src/setup-mage.sh
        environment:
            - MAGE_SETUP_DB_HOST=percona
            - MAGE_SETUP_DB_NAME=MAGE_TWO
            - MAGE_SETUP_DB_USER=mage
            - MAGE_SETUP_DB_PASSWORD=123
            - MAGE_SETUP_BASE_URL=http://it.mage-two/
            - MAGE_SETUP_ADMIN_BACKEND_FRONTNAME=admin
            - MAGE_SETUP_ADMIN_FIRSTNAME=Owner
            - MAGE_SETUP_ADMIN_LASTNAME=Mage
            - MAGE_SETUP_ADMIN_EMAIL=owner@mage.com
            - MAGE_SETUP_ADMIN_USER=admin
            - MAGE_SETUP_ADMIN_PASSWORD=12345qw
        networks:
            - network-back
   
    percona:
        image: percona
        restart: always
        volumes:
            - ./docker/mysql/data/percona:/var/lib/mysql
            - ./docker/mysql/dumps:/dumps
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=MAGE_TWO
            - MYSQL_USER=mage
            - MYSQL_PASSWORD=123
        networks:
            - network-back

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        container_name: phpmyadmin_development
        environment:
            PMA_ARBITRARY: 1
        ports:
            - 8888:80
        volumes:
            - /sessions
        networks:
            - network-back
    redis:
        image: redis
        restart: always
        ports:
          - 6379:6379
        networks:
            - network-back

    mailhog:
        image: mailhog/mailhog:latest
        restart: always
        ports:
          - "1025:1025"
          - "8025:8025"
        networks:
          - network-back

networks:
    network-back:
        driver: bridge